version: '3'
services:
  springdemo:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: DomoVeno4ek
      MYSQL_DATABASE: blog
      MYSQL_USER: root
      MYSQL_PASSWORD: DomoVeno4ek
volumes:
  db_data: {}